program: train.py
method: random
metric:
  name: val_accuracy
  goal: maximize
parameters:
  pre_training_learning_rate:
    min: 0.0001
    max: 1
  max_epochs_per_fit:
    distribution: int_uniform
    min: 10
    max: 20
  fine_tuning_learning_rate: 
    min: 1e-5
    max: 1e-2
  fine_tuning_min_delta: 
    min: 0
    max: 0.1
  fine_tuning_patience: 
    distribution: int_uniform
    min: 0
    max: 10
  fine_tuning_unfreeze_interval: 
    min: 10
    max: 50
  max_epochs: 
    value: 50
early_terminate:
  type: hyperband

  