program: /macierz/home/s165115/mgr/NNUtils/train.py
method: grid
project: lego-4h
metric:
  name: val_accuracy
  goal: maximize
parameters:
  json:
    values: [
      "/macierz/home/s165115/mgr/NNUtils/configs/train/tl_4h.json"
    ]
  net_json:
    values: [
      "/macierz/home/s165115/mgr/NNUtils/configs/train/networks/ResNet50.json",
      "/macierz/home/s165115/mgr/NNUtils/configs/train/networks/VGG16.json",
    ]